# Generated by Django 5.1.1 on 2024-12-07 20:06

import propiedades.nube
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='constancia_universidad',
            field=models.FileField(storage=propiedades.nube.MediaStorage(), upload_to='constancias_estudio/'),
        ),
    ]
