# Generated by Django 5.1.1 on 2024-12-12 23:43

import propiedades.nube
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_estudiante_constancia_universidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, storage=propiedades.nube.MediaStorage(), upload_to='profile_pictures/'),
        ),
    ]
