# Generated by Django 5.1.1 on 2024-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
