# Generated by Django 5.1.1 on 2024-11-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0002_propiedad_nombre'),
        ('usuarios', '0002_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
        ),
    ]
