# Generated by Django 5.1.1 on 2024-12-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
    ]
